// 200 citations sur la démocratisation de l'IA - Franklin KAMCHE
// Chaque citation a une police Google Fonts différente

export interface Citation {
  text: string
  font: string
}

export const citations: Citation[] = [
  { text: "L'IA n'est pas réservée aux génies, elle appartient à tous ceux qui osent apprendre.", font: "Merriweather" },
  { text: "Démocratiser l'intelligence artificielle, c'est offrir à chacun les clés du futur.", font: "Playfair Display" },
  { text: "Le savoir de demain doit être accessible aujourd'hui.", font: "Lora" },
  { text: "L'IA est un outil, pas un privilège.", font: "Crimson Text" },
  { text: "Comprendre l'IA, c'est reprendre le contrôle de son avenir.", font: "Libre Baskerville" },
  { text: "Chaque esprit curieux mérite d'accéder à la révolution technologique.", font: "Source Serif Pro" },
  { text: "L'intelligence artificielle parle toutes les langues quand on prend le temps de l'expliquer.", font: "Cormorant Garamond" },
  { text: "Rendre l'IA accessible, c'est investir dans l'humanité.", font: "EB Garamond" },
  { text: "Le futur appartient à ceux qui comprennent le présent.", font: "Spectral" },
  { text: "L'IA sans pédagogie est un trésor enfermé.", font: "Bitter" },
  { text: "Apprendre l'IA, c'est apprendre à penser autrement.", font: "Alegreya" },
  { text: "La technologie avance, l'éducation doit suivre.", font: "Vollkorn" },
  { text: "Chaque ligne de code peut changer une vie.", font: "Noto Serif" },
  { text: "L'IA accessible est une IA responsable.", font: "Josefin Slab" },
  { text: "Démystifier l'IA, c'est libérer les esprits.", font: "Cardo" },
  { text: "Le génie est dans la simplicité de l'explication.", font: "Old Standard TT" },
  { text: "L'avenir se construit avec ceux qui comprennent.", font: "Sorts Mill Goudy" },
  { text: "Pas besoin d'être ingénieur pour maîtriser l'IA.", font: "Gentium Book Basic" },
  { text: "L'IA est un langage universel qui s'apprend.", font: "Neuton" },
  { text: "Chaque francophone mérite sa place dans la révolution IA.", font: "Domine" },
  { text: "La connaissance partagée multiplie les possibilités.", font: "Amiri" },
  { text: "L'IA n'exclut personne quand elle est bien enseignée.", font: "Noticia Text" },
  { text: "Transformer la complexité en clarté, c'est notre mission.", font: "Arvo" },
  { text: "L'intelligence artificielle est le nouveau langage du monde.", font: "Rokkitt" },
  { text: "Apprendre, comprendre, maîtriser : le chemin vers l'IA.", font: "Slabo 27px" },
  { text: "L'IA accessible ouvre des portes insoupçonnées.", font: "Quattrocento" },
  { text: "Le savoir technique n'a pas de frontières.", font: "Prata" },
  { text: "Chaque cerveau est prêt pour l'IA, il suffit de l'éveiller.", font: "Glegoo" },
  { text: "La démocratisation du savoir est la plus belle des révolutions.", font: "Faustina" },
  { text: "L'IA de demain s'apprend aujourd'hui.", font: "Karma" },
  { text: "Ouvrir les portes de l'IA, c'est ouvrir les portes de l'emploi.", font: "Aleo" },
  { text: "L'ignorance est le seul obstacle à la maîtrise de l'IA.", font: "Vidaloka" },
  { text: "Chaque tutoriel est une graine de savoir plantée.", font: "Halant" },
  { text: "L'IA expliquée simplement change des vies concrètement.", font: "Tinos" },
  { text: "Le monde numérique appartient à ceux qui le comprennent.", font: "Lusitana" },
  { text: "Vulgariser n'est pas simplifier, c'est clarifier.", font: "Crete Round" },
  { text: "L'IA est un voyage, pas une destination.", font: "Abhaya Libre" },
  { text: "Chaque question posée est un pas vers la maîtrise.", font: "Podkova" },
  { text: "L'excellence technique commence par les fondamentaux.", font: "Cambo" },
  { text: "L'IA inclusive est l'IA du futur.", font: "Vesper Libre" },
  { text: "Le code n'a pas de couleur, l'IA n'a pas de frontière.", font: "Eczar" },
  { text: "Apprendre l'IA, c'est investir en soi-même.", font: "Trirong" },
  { text: "La peur de l'IA disparaît avec la compréhension.", font: "Zilla Slab" },
  { text: "Chaque concept maîtrisé est une victoire personnelle.", font: "Petrona" },
  { text: "L'IA n'est difficile que pour ceux qui n'ont pas eu de bon professeur.", font: "Markazi Text" },
  { text: "Le savoir partagé est le savoir multiplié.", font: "Brawler" },
  { text: "L'IA accessible construit des ponts entre les générations.", font: "Quando" },
  { text: "Chaque apprenant d'aujourd'hui est un expert de demain.", font: "Junge" },
  { text: "L'intelligence artificielle attend juste d'être comprise.", font: "Sanchez" },
  { text: "Le futur s'écrit avec ceux qui osent apprendre.", font: "Suez One" },
  { text: "L'IA est un amplificateur de potentiel humain.", font: "Pridi" },
  { text: "Démocratiser, c'est donner le pouvoir à tous.", font: "Buenard" },
  { text: "L'IA sans barrière est l'IA qui fait progresser l'humanité.", font: "Fenix" },
  { text: "Chaque livre est une porte vers l'avenir.", font: "Bentham" },
  { text: "L'IA accessible est un droit, pas un luxe.", font: "Andada" },
  { text: "Comprendre pour créer, apprendre pour innover.", font: "Inika" },
  { text: "L'IA expliquée est l'IA adoptée.", font: "Unna" },
  { text: "Le savoir technique démocratisé est une force collective.", font: "Kurale" },
  { text: "Chaque formation suivie rapproche du succès.", font: "Oranienbaum" },
  { text: "L'IA sans mystère est l'IA maîtrisée.", font: "Average" },
  { text: "Le monde de demain récompensera les curieux d'aujourd'hui.", font: "Habibi" },
  { text: "L'IA est un outil d'émancipation intellectuelle.", font: "GFS Didot" },
  { text: "Chaque concept appris est une compétence gagnée.", font: "Rufina" },
  { text: "L'avenir numérique se construit brique par brique.", font: "Radley" },
  { text: "L'IA accessible transforme les spectateurs en acteurs.", font: "Alike" },
  { text: "Le savoir n'a de valeur que s'il est partagé.", font: "Linden Hill" },
  { text: "L'IA démystifiée est l'IA humanisée.", font: "Esteban" },
  { text: "Chaque étape franchie renforce la confiance.", font: "Almendra" },
  { text: "L'intelligence artificielle est l'alphabet du XXIe siècle.", font: "Gilda Display" },
  { text: "Apprendre l'IA, c'est se préparer à tous les métiers de demain.", font: "Gabriela" },
  { text: "L'IA accessible est la promesse d'un monde plus équitable.", font: "Adamina" },
  { text: "Chaque tutoriel visionné est un pas vers l'autonomie.", font: "Poly" },
  { text: "L'IA n'attend que des esprits prêts à la découvrir.", font: "Ledger" },
  { text: "Le futur appartient aux autodidactes éclairés.", font: "Rosarivo" },
  { text: "L'IA accessible libère le potentiel de chacun.", font: "Yrsa" },
  { text: "Chaque formation est un investissement dans l'avenir.", font: "Copse" },
  { text: "L'IA comprise est l'IA apprivoisée.", font: "Mate" },
  { text: "Le savoir technique est le nouveau pouvoir.", font: "Fauna One" },
  { text: "L'IA accessible crée des opportunités infinies.", font: "Kreon" },
  { text: "Chaque livre lu ouvre de nouvelles perspectives.", font: "Imprima" },
  { text: "L'intelligence artificielle attend d'être démocratisée.", font: "Cantata One" },
  { text: "Apprendre l'IA, c'est prendre son destin en main.", font: "Antic Didone" },
  { text: "L'IA accessible est le fondement d'une société juste.", font: "Enriqueta" },
  { text: "Chaque concept maîtrisé est un outil gagné.", font: "Fjord One" },
  { text: "L'IA n'est pas le futur, elle est le présent à comprendre.", font: "Headland One" },
  { text: "Le savoir partagé construit des ponts, pas des murs.", font: "Italiana" },
  { text: "L'IA accessible est une révolution silencieuse.", font: "Judson" },
  { text: "Chaque apprenant est un ambassadeur du savoir.", font: "Kadwa" },
  { text: "L'intelligence artificielle est une langue qui s'apprend.", font: "Laila" },
  { text: "Démocratiser l'IA, c'est préparer le monde de demain.", font: "Martel" },
  { text: "L'IA accessible transforme les rêves en projets.", font: "Neucha" },
  { text: "Chaque question posée est une opportunité d'apprendre.", font: "Ovo" },
  { text: "L'IA comprise est l'IA qui sert l'humanité.", font: "Philosopher" },
  { text: "Le futur récompense ceux qui se préparent.", font: "Sahitya" },
  { text: "L'IA accessible est un catalyseur de changement.", font: "Sumana" },
  { text: "Chaque connaissance acquise est une liberté gagnée.", font: "Trocchi" },
  { text: "L'intelligence artificielle n'a pas de secret pour qui veut apprendre.", font: "Ultra" },
  { text: "Le savoir technique démocratisé change le monde.", font: "Antic Slab" },
  { text: "L'IA accessible ouvre les portes de l'innovation.", font: "Coustard" },
  { text: "Chaque formation suivie construit l'avenir.", font: "Donegal One" },
  { text: "L'IA n'est complexe que pour ceux qui n'ont pas commencé.", font: "Fraunces" },
  { text: "Le monde numérique attend ses nouveaux acteurs.", font: "Gelasio" },
  { text: "L'IA accessible est le socle de l'égalité des chances.", font: "Ibarra Real Nova" },
  { text: "Chaque page tournée rapproche de la maîtrise.", font: "Jomolhari" },
  { text: "L'intelligence artificielle se démocratise un lecteur à la fois.", font: "Kotta One" },
  { text: "Apprendre l'IA, c'est s'ouvrir au monde.", font: "Literata" },
  { text: "L'IA accessible construit des leaders de demain.", font: "Martel Sans" },
  { text: "Chaque tutoriel est une victoire sur l'ignorance.", font: "Newsreader" },
  { text: "Le savoir technique n'a jamais été aussi accessible.", font: "Piazzolla" },
  { text: "L'IA démocratisée est l'IA qui progresse.", font: "Rasa" },
  { text: "Chaque compétence acquise est un pas vers l'emploi.", font: "Scheherazade New" },
  { text: "L'intelligence artificielle attend ses prochains talents.", font: "Scope One" },
  { text: "Le futur s'apprend aujourd'hui.", font: "Sura" },
  { text: "L'IA accessible est une promesse tenue.", font: "Taviraj" },
  { text: "Chaque concept expliqué simplifie le monde.", font: "Corben" },
  { text: "L'IA comprise ouvre des horizons infinis.", font: "BioRhyme" },
  { text: "Le savoir partagé est le plus beau des héritages.", font: "Caudex" },
  { text: "L'IA accessible est un droit universel.", font: "Chivo" },
  { text: "Chaque formation crée de nouvelles possibilités.", font: "DM Serif Display" },
  { text: "L'intelligence artificielle est le nouveau langage commun.", font: "Frank Ruhl Libre" },
  { text: "Démocratiser l'IA, c'est démocratiser l'avenir.", font: "Hepta Slab" },
  { text: "L'IA accessible transforme les curieux en experts.", font: "IBM Plex Serif" },
  { text: "Chaque livre est un compagnon vers la maîtrise.", font: "Inria Serif" },
  { text: "Le monde numérique n'attend que vous.", font: "Josefin Sans" },
  { text: "L'IA démystifiée est l'IA adoptée par tous.", font: "Kumbh Sans" },
  { text: "Chaque étape d'apprentissage est une victoire.", font: "Libre Caslon Text" },
  { text: "L'intelligence artificielle est à la portée de tous.", font: "Manrope" },
  { text: "Le savoir technique démocratisé crée des opportunités.", font: "Nunito" },
  { text: "L'IA accessible est la clé de l'innovation.", font: "Open Sans" },
  { text: "Chaque question est le début d'une réponse.", font: "Overpass" },
  { text: "L'IA comprise change les perspectives.", font: "PT Sans" },
  { text: "Le futur appartient aux apprenants.", font: "Quattrocento Sans" },
  { text: "L'IA accessible construit la société de demain.", font: "Red Hat Display" },
  { text: "Chaque connaissance partagée multiplie les talents.", font: "Roboto" },
  { text: "L'intelligence artificielle n'a plus de secrets.", font: "Source Sans Pro" },
  { text: "Démocratiser le savoir, c'est démocratiser le pouvoir.", font: "Space Grotesk" },
  { text: "L'IA accessible est un tremplin vers le succès.", font: "Urbanist" },
  { text: "Chaque tutoriel est une porte vers l'avenir.", font: "Work Sans" },
  { text: "Le monde technique attend ses nouveaux talents.", font: "Archivo" },
  { text: "L'IA démocratisée est l'IA humanisée.", font: "Barlow" },
  { text: "Chaque formation est un pas vers l'excellence.", font: "Be Vietnam Pro" },
  { text: "L'intelligence artificielle s'apprend, se comprend, se maîtrise.", font: "Cabin" },
  { text: "Le savoir accessible crée des leaders.", font: "Commissioner" },
  { text: "L'IA accessible est une révolution éducative.", font: "DM Sans" },
  { text: "Chaque page lue rapproche du but.", font: "Encode Sans" },
  { text: "L'IA comprise est l'IA qui transforme.", font: "Fira Sans" },
  { text: "Le futur se prépare maintenant.", font: "Heebo" },
  { text: "L'IA accessible ouvre le champ des possibles.", font: "IBM Plex Sans" },
  { text: "Chaque concept appris est une force gagnée.", font: "Inter" },
  { text: "L'intelligence artificielle attend d'être apprise.", font: "Jost" },
  { text: "Le savoir partagé construit l'avenir.", font: "Karla" },
  { text: "L'IA démocratisée transforme les vies.", font: "Lato" },
  { text: "Chaque apprenant est un futur innovateur.", font: "Lexend" },
  { text: "L'IA accessible est le fondement du progrès.", font: "Libre Franklin" },
  { text: "Le monde de demain appartient aux curieux.", font: "Maven Pro" },
  { text: "L'intelligence artificielle se démocratise.", font: "Montserrat" },
  { text: "Chaque formation ouvre des portes.", font: "Mulish" },
  { text: "L'IA comprise est l'IA maîtrisée.", font: "Noto Sans" },
  { text: "Le savoir technique n'exclut personne.", font: "Outfit" },
  { text: "L'IA accessible crée des opportunités pour tous.", font: "Oxanium" },
  { text: "Chaque tutoriel rapproche de l'expertise.", font: "Poppins" },
  { text: "L'intelligence artificielle est universelle.", font: "Public Sans" },
  { text: "Démocratiser, éduquer, transformer.", font: "Quicksand" },
  { text: "L'IA accessible est une chance pour tous.", font: "Rajdhani" },
  { text: "Chaque livre est un mentor.", font: "Rubik" },
  { text: "Le futur s'écrit avec le savoir.", font: "Sora" },
  { text: "L'IA démystifiée ouvre des horizons.", font: "Spartan" },
  { text: "Chaque question trouve sa réponse.", font: "Titillium Web" },
  { text: "L'intelligence artificielle n'attend que vous.", font: "Ubuntu" },
  { text: "Le savoir accessible change le monde.", font: "Varela Round" },
  { text: "L'IA accessible est notre mission.", font: "Yantramanav" },
  { text: "Chaque étape compte dans l'apprentissage.", font: "Saira" },
  { text: "L'IA comprise transforme les rêves en réalité.", font: "Signika" },
  { text: "Le monde numérique s'ouvre à tous.", font: "Prompt" },
  { text: "L'IA accessible construit l'avenir.", font: "Assistant" },
  { text: "Chaque connaissance est une liberté.", font: "Asap" },
  { text: "L'intelligence artificielle pour tous, par tous.", font: "Hind" },
  { text: "Démocratiser l'IA, c'est changer le monde.", font: "Exo 2" },
  { text: "L'IA accessible libère les potentiels.", font: "Cairo" },
  { text: "Chaque formation est un pas vers demain.", font: "Catamaran" },
  { text: "Le savoir partagé illumine l'avenir.", font: "Nunito Sans" },
  { text: "L'IA démocratisée est notre héritage.", font: "Sarabun" },
  { text: "Chaque apprenant écrit l'histoire.", font: "Kanit" },
]

// Fonction pour charger dynamiquement les polices
export const loadFont = (fontName: string) => {
  const link = document.createElement('link')
  link.href = `https://fonts.googleapis.com/css2?family=${fontName.replace(/ /g, '+')}:ital,wght@1,400&display=swap`
  link.rel = 'stylesheet'
  document.head.appendChild(link)
}
